apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-frontend
  template:
    metadata:
      labels:
        app: brain-frontend
    spec:
      containers:
        - name: brain-frontend
          image: madhavgirdhar/bt-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: brain-frontend-service
spec:
  type: NodePort
  selector:
    app: brain-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30040