---
- name: Apply frontend manifest
  shell: |
    KUBECONFIG={{ kubeconfig_dest }} \
    kubectl apply -f {{ deployment_file }} --validate=false
  register: apply_out

- debug:
    var: apply_out.stdout_lines

- name: Notify restart
  debug:
    msg: "Restarting deployment"
  notify: Restart Brain Frontend
  changed_when: true

  
